import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Map;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * This class is used for testing subimages generated by gridCreateTest. 
 * In particular, we verify that the hashmap of subimages is correctly generated.
 */

public class DisplayImage {

    public static void main(String avg[]) throws IOException
    {
        DisplayImage abc=new DisplayImage();
    }

    public DisplayImage() throws IOException
    {
    	File f = new File("hs-2006-10-a-full_jpg.jpg"); 
        boolean exists = f.exists(); 
        BufferedImage bufferedImage = ImageIO.read(f);
    	GridCreateTest GCT = new GridCreateTest(bufferedImage, 1000, 400, 450);  
    	Map<String, BufferedImage> images = GCT.makeGrid();
        for (Map.Entry<String, BufferedImage> entry : images.entrySet()){
        	
        	ImageIcon icon=new ImageIcon(entry.getValue());

        	JFrame frame=new JFrame();
            frame.setLayout(new FlowLayout());
            frame.setSize(1000,1000);
            JLabel lbl=new JLabel();
            lbl.setIcon(icon);
            frame.add(lbl);
            frame.setVisible(true);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        	try {
				Thread.sleep(4000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
        }
        
    }
}